# Generated by Django 3.2.3 on 2021-06-08 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jan_QR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cr_jan_01', models.IntegerField(blank=True, null=True, verbose_name='janコード生成')),
                ('cr_qr_01', models.CharField(blank=True, max_length=255, null=True, verbose_name='QRコード生成')),
            ],
            options={
                'verbose_name': 'JANコード, QRコード生成',
                'verbose_name_plural': 'JANコード, QRコード生成',
            },
        ),
        migrations.CreateModel(
            name='Maker_master',
            fields=[
                ('maker_code', models.IntegerField(default=0, primary_key=True, serialize=False, verbose_name='メーカーコード')),
                ('maker_name', models.CharField(default='', max_length=40, verbose_name='メーカー名')),
                ('hanbaiten', models.CharField(blank=True, default='', max_length=40, verbose_name='販売店')),
                ('maker_code_url', models.CharField(blank=True, default='', max_length=200, verbose_name='URL')),
                ('web_maker_keyword', models.CharField(blank=True, default='', max_length=200, verbose_name='キーワード')),
            ],
            options={
                'verbose_name': 'メーカーコード登録',
                'verbose_name_plural': 'メーカーコード登録',
            },
        ),
        migrations.CreateModel(
            name='Medium_category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Medium_code', models.IntegerField(unique=True, verbose_name='品名カテゴリーコード')),
                ('Medium_title', models.CharField(max_length=100, verbose_name='品名カテゴリータイトル')),
                ('Medium_image', models.ImageField(blank=True, default=None, null=True, upload_to='images/uploaded/category_01/')),
                ('M_code', models.IntegerField(blank=True, null=True, verbose_name='上記で選択した番号を入力してください。')),
            ],
            options={
                'verbose_name': '品名カテゴリー',
                'verbose_name_plural': '品名カテゴリー',
            },
        ),
        migrations.CreateModel(
            name='Original_Cate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_cate_code', models.IntegerField(verbose_name='オリジナルカテゴリーコード')),
                ('original_cate_name', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='オリジナルカテゴリー名')),
                ('original_cate_thumbnail', models.ImageField(blank=True, default=None, null=True, upload_to='images/uploaded/category_original/')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_title', models.CharField(default='', max_length=100, null=True, verbose_name='新着タイトル')),
                ('text', models.TextField(default='', null=True, verbose_name='新着ニュース')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='images/uploaded/top_slide/', verbose_name='サムネイル')),
                ('name', models.CharField(blank=True, default='', max_length=30, null=True, verbose_name='スライダー名')),
                ('price', models.IntegerField(blank=True, default=0, null=True, verbose_name='価格')),
                ('description', models.TextField(blank=True, default='', null=True, verbose_name='説明')),
            ],
            options={
                'verbose_name': 'スライダー画像',
                'verbose_name_plural': 'スライダー画像',
            },
        ),
        migrations.CreateModel(
            name='Test_shouhin_01',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Test_shouhin_01_code', models.CharField(default='', max_length=50, verbose_name='メーカーコード')),
                ('Test_shouhin_01_name', models.CharField(default='', max_length=50, verbose_name='メーカー名')),
                ('Test_shouhin_01_str', models.CharField(default='', max_length=100, null=True, verbose_name='商品名')),
                ('Test_shouhin_01_image', models.ImageField(blank=True, default=None, null=True, upload_to='images/img_test_01/')),
            ],
            options={
                'verbose_name': 'テスト商品登録01',
                'verbose_name_plural': 'テスト商品登録01',
            },
        ),
        migrations.CreateModel(
            name='Toriatukai_Cate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Toriatukai_code', models.IntegerField(default=0, unique=True, verbose_name='取扱商品コード（WEB表示用）')),
                ('Toriatukai_title', models.CharField(default='', max_length=50, verbose_name='取扱商品 タイトル（WEB表示用）')),
            ],
            options={
                'verbose_name': '取扱カテゴリー登録',
                'verbose_name_plural': '取扱カテゴリー登録',
            },
        ),
        migrations.CreateModel(
            name='Test_shouhin_010',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Test_shouhin_010_code', models.CharField(max_length=50, verbose_name='メーカーコード')),
                ('Test_shouhin_010_name', models.CharField(max_length=50, verbose_name='メーカー名')),
                ('Test_shouhin_010_str', models.CharField(max_length=100, verbose_name='商品名')),
                ('Test_shouhin_010_code_02', models.CharField(blank=True, max_length=100, null=True, verbose_name='メーカー小カテゴリーコード')),
                ('Test_shouhin_010_name_02', models.CharField(blank=True, max_length=100, null=True, verbose_name='メーカー小カテゴリーコード')),
                ('Test_shouhin_010_image', models.ImageField(blank=True, default=None, null=True, upload_to='images/uploaded/shouhin/')),
                ('jan_code', models.IntegerField(default=0, verbose_name='JANコード')),
                ('counter', models.CharField(default='', max_length=50, verbose_name='カウンター')),
                ('search_hinmei', models.CharField(blank=True, default='', max_length=150, null=True, verbose_name='検索用品名')),
                ('description_item', models.TextField(blank=True, default='', max_length=255, null=True, verbose_name='商品説明')),
                ('kikaku', models.CharField(default='', max_length=50, verbose_name='検索用品名')),
                ('siyou_name_01', models.CharField(blank=True, default='', max_length=150, null=True, verbose_name='仕様名称 01')),
                ('siyou_content_01', models.TextField(blank=True, default='', max_length=255, null=True, verbose_name='仕様内容 01')),
                ('siyou_name_02', models.CharField(blank=True, default='', max_length=150, null=True, verbose_name='仕様名称 02')),
                ('siyou_content_02', models.TextField(blank=True, default='', max_length=255, null=True, verbose_name='仕様内容 02')),
                ('siyou_name_03', models.CharField(blank=True, default='', max_length=150, null=True, verbose_name='仕様名称 03')),
                ('siyou_content_03', models.TextField(blank=True, default='', max_length=255, null=True, verbose_name='仕様内容 03')),
                ('siyou_name_04', models.CharField(blank=True, default='', max_length=150, null=True, verbose_name='仕様名称 04')),
                ('siyou_content_04', models.TextField(blank=True, default='', max_length=255, null=True, verbose_name='仕様内容 04')),
                ('siyou_name_05', models.CharField(blank=True, default='', max_length=150, null=True, verbose_name='仕様名称 05')),
                ('siyou_content_05', models.TextField(blank=True, default='', max_length=255, null=True, verbose_name='仕様内容 05')),
                ('haiban_flg', models.IntegerField(blank=True, default=0, null=True, verbose_name='廃盤 F')),
                ('sh_thumbnail_02', models.ImageField(blank=True, default=None, null=True, upload_to='images/uploaded/shouhin/')),
                ('sh_thumbnail_03', models.ImageField(blank=True, default=None, null=True, upload_to='images/uploaded/shouhin/')),
                ('shouhin_flg', models.IntegerField(choices=[(0, '通常商品'), (1, 'オリジナル商品'), (2, 'おすすめ商品')], default=0, verbose_name='商品選別 フラグ')),
                ('T_Medium_code_02', models.ForeignKey(db_column='T_Medium_code', on_delete=django.db.models.deletion.CASCADE, to='kanai_app.medium_category', to_field='Medium_code', verbose_name='品名カテゴリー')),
            ],
            options={
                'verbose_name': 'テスト商品登録01',
                'verbose_name_plural': 'テスト商品登録01',
            },
        ),
        migrations.AddField(
            model_name='medium_category',
            name='M_Toriatukai_code',
            field=models.ForeignKey(db_column='M_Toriatukai_code', on_delete=django.db.models.deletion.CASCADE, to='kanai_app.toriatukai_cate', to_field='Toriatukai_code', verbose_name='取扱品コード'),
        ),
        migrations.CreateModel(
            name='Brand_master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_code', models.IntegerField(default=0, verbose_name='ブランドコード')),
                ('brand_name', models.CharField(default='', max_length=40, verbose_name='ブランド名')),
                ('web_brand_keyword', models.CharField(blank=True, default='', max_length=200, verbose_name='キーワード')),
                ('b_maker_code', models.ForeignKey(db_column='b_maker_code', on_delete=django.db.models.deletion.CASCADE, to='kanai_app.maker_master', verbose_name='メーカーコード')),
            ],
            options={
                'verbose_name': 'ブランド登録',
                'verbose_name_plural': 'ブランド登録',
            },
        ),
        migrations.CreateModel(
            name='Agency_master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agency_code', models.IntegerField(default=0, verbose_name='代理店コード')),
                ('agency_name', models.CharField(default='', max_length=40, verbose_name='代理店名')),
                ('web_agency_keyword', models.CharField(blank=True, max_length=200, verbose_name='キーワード')),
                ('a_maker_code', models.ForeignKey(db_column='a_maker_code', on_delete=django.db.models.deletion.CASCADE, to='kanai_app.maker_master', verbose_name='メーカーコード')),
            ],
            options={
                'verbose_name': '代理店登録',
                'verbose_name_plural': '代理店登録',
            },
        ),
    ]
